import { Link } from 'react-router-dom'
import { Button } from '@/components/ui/Button'

const features = [
  {
    icon: (
      <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <path d="M12 2v20M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"/>
      </svg>
    ),
    title: 'Track Expenses Effortlessly',
    desc: 'Add transactions in seconds. Categorize spending with color-coded icons. See where every dollar goes at a glance.',
  },
  {
    icon: (
      <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/>
      </svg>
    ),
    title: 'Smart Budgets',
    desc: 'Set monthly limits per category. Get alerts before you overspend. Stay on track with real-time progress bars.',
  },
  {
    icon: (
      <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <polyline points="22 12 18 12 15 21 9 3 6 12 2 12"/>
      </svg>
    ),
    title: 'Deep Analytics',
    desc: 'Visualize spending trends over 6 months. Breakdown by category. Spot patterns and find savings opportunities.',
  },
  {
    icon: (
      <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/>
        <polyline points="3.27 6.96 12 12.01 20.73 6.96"/><line x1="12" y1="22.08" x2="12" y2="12"/>
      </svg>
    ),
    title: 'AI-Powered Insights',
    desc: 'Get a monthly summary generated by AI. Receive spending predictions. Let AI suggest smart budget amounts.',
  },
  {
    icon: (
      <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <rect x="3" y="11" width="18" height="11" rx="2" ry="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/>
      </svg>
    ),
    title: 'Private & Secure',
    desc: 'Your financial data is encrypted and never shared. We do not sell or share your information with third parties.',
  },
  {
    icon: (
      <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/>
        <path d="M23 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/>
      </svg>
    ),
    title: 'Built for Everyone',
    desc: 'Student or professional — PennyWise adapts to your lifestyle. Track in USD or VND with a clean, modern interface.',
  },
]

const steps = [
  {
    num: '01',
    title: 'Create your free account',
    desc: 'Sign up in 30 seconds. No credit card required. Your data is ready instantly.',
  },
  {
    num: '02',
    title: 'Add your transactions',
    desc: 'Log expenses as they happen. Use quick-amount buttons or enter custom values. Categorize with one tap.',
  },
  {
    num: '03',
    title: 'Set smart budgets',
    desc: 'Choose monthly limits for each category. Let AI suggest optimal amounts based on your spending habits.',
  },
  {
    num: '04',
    title: 'Watch your savings grow',
    desc: 'Review analytics weekly. Generate AI insights. Adjust budgets and celebrate hitting your goals.',
  },
]

export function AboutPage() {
  return (
    <div className="min-h-screen bg-[#0A0A0A] text-white">

      {/* Nav */}
      <nav className="flex items-center justify-between px-6 lg:px-12 py-5 border-b border-[#262626]">
        <div className="flex items-center gap-2.5">
          <div className="w-9 h-9 rounded-xl bg-[#BFFF00] flex items-center justify-center">
            <span className="text-[#0A0A0A] font-bold text-base">P</span>
          </div>
          <span className="font-semibold text-white text-lg">PennyWise</span>
        </div>
        <div className="flex items-center gap-3">
          <Link to="/login">
            <Button variant="ghost" size="sm" className="!text-white">Sign In</Button>
          </Link>
          <Link to="/register">
            <Button variant="gradient" size="sm">Get Started</Button>
          </Link>
        </div>
      </nav>

      {/* Hero */}
      <section className="px-6 lg:px-12 py-20 lg:py-28 text-center">
        <div className="max-w-3xl mx-auto">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-neutral-800 border border-[#262626] mb-8">
            <span className="w-2 h-2 rounded-full bg-[#BFFF00] animate-pulse" />
            <span className="text-sm text-text-secondary">Free forever — no credit card needed</span>
          </div>
          <h1 className="text-5xl lg:text-7xl font-extrabold text-white leading-tight mb-6">
            Your finances,<br />
            <span className="text-[#BFFF00]">finally under control</span>
          </h1>
          <p className="text-lg text-text-secondary leading-relaxed mb-10 max-w-xl mx-auto">
            PennyWise is an AI-powered personal finance tracker that helps you track expenses, set smart budgets, and grow your savings — without the complexity.
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <Link to="/register">
              <Button variant="gradient" size="lg" className="w-full sm:w-auto">
                Get Started — It's Free
              </Button>
            </Link>
            <Link to="/login">
              <Button variant="outline" size="lg" className="w-full sm:w-auto">
                I Have an Account
              </Button>
            </Link>
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="px-6 lg:px-12 py-20 border-t border-[#262626]">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-3xl lg:text-4xl font-extrabold text-white mb-4">
              Everything you need to manage money
            </h2>
            <p className="text-text-secondary max-w-lg mx-auto">
              Simple, powerful tools designed to make financial tracking effortless and even enjoyable.
            </p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map((f) => (
              <div
                key={f.title}
                className="p-6 rounded-2xl bg-[#171717] border border-[#262626] hover:border-[#404040] transition-all duration-200 group"
              >
                <div className="w-14 h-14 rounded-xl bg-neutral-800 flex items-center justify-center text-[#BFFF00] mb-5 group-hover:bg-[#BFFF00] group-hover:text-[#0A0A0A] transition-all duration-200">
                  {f.icon}
                </div>
                <h3 className="text-base font-bold text-white mb-2">{f.title}</h3>
                <p className="text-sm text-text-secondary leading-relaxed">{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How it works */}
      <section className="px-6 lg:px-12 py-20 border-t border-[#262626]">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-3xl lg:text-4xl font-extrabold text-white mb-4">
              Up and running in minutes
            </h2>
            <p className="text-text-secondary">
              No spreadsheets. No complexity. Just you and your money.
            </p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {steps.map((s) => (
              <div key={s.num} className="text-center lg:text-left">
                <div className="text-5xl font-extrabold text-[#262626] mb-4 select-none">{s.num}</div>
                <h3 className="text-base font-bold text-white mb-2">{s.title}</h3>
                <p className="text-sm text-text-secondary leading-relaxed">{s.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section className="px-6 lg:px-12 py-20 border-t border-[#262626]">
        <div className="max-w-3xl mx-auto text-center">
          <h2 className="text-3xl lg:text-4xl font-extrabold text-white mb-4">
            Simple, transparent pricing
          </h2>
          <p className="text-text-secondary mb-12">
            Start free. Upgrade when you need more.
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 max-w-2xl mx-auto">
            {/* Free */}
            <div className="p-8 rounded-2xl bg-[#171717] border border-[#262626] text-left">
              <div className="text-sm font-semibold text-text-secondary uppercase tracking-wider mb-3">Free</div>
              <div className="flex items-end gap-1 mb-6">
                <span className="text-5xl font-extrabold text-white">$0</span>
                <span className="text-text-secondary mb-2">/forever</span>
              </div>
              <ul className="space-y-3 mb-8">
                {['Unlimited transactions', 'Budget tracking', '6-month analytics', 'AI monthly summary', 'Multiple categories'].map(item => (
                  <li key={item} className="flex items-center gap-3 text-sm text-text-secondary">
                    <svg className="w-4 h-4 text-[#BFFF00] flex-shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                      <polyline points="20 6 9 17 4 12"/>
                    </svg>
                    {item}
                  </li>
                ))}
              </ul>
              <Link to="/register" className="block">
                <Button variant="outline" className="w-full">Get Started</Button>
              </Link>
            </div>
            {/* Pro */}
            <div className="p-8 rounded-2xl bg-[#BFFF00] border border-[#BFFF00] text-left relative">
              <div className="absolute -top-3 left-6 px-3 py-1 rounded-full bg-[#0A0A0A] text-xs font-bold text-[#BFFF00]">
                COMING SOON
              </div>
              <div className="text-sm font-semibold text-[#0A0A0A] uppercase tracking-wider mb-3">Pro</div>
              <div className="flex items-end gap-1 mb-6">
                <span className="text-5xl font-extrabold text-[#0A0A0A]">$5</span>
                <span className="text-[#0A0A0A]/60 mb-2">/month</span>
              </div>
              <ul className="space-y-3 mb-8">
                {['Everything in Free', 'AI budget suggestions', 'Export to CSV / PDF', 'Multiple currencies', 'Priority support'].map(item => (
                  <li key={item} className="flex items-center gap-3 text-sm text-[#0A0A0A]">
                    <svg className="w-4 h-4 text-[#0A0A0A] flex-shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                      <polyline points="20 6 9 17 4 12"/>
                    </svg>
                    {item}
                  </li>
                ))}
              </ul>
              <Button variant="primary" className="w-full !bg-[#0A0A0A] !text-[#BFFF00] !hover:bg-[#171717]" disabled>
                Coming Soon
              </Button>
            </div>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="px-6 lg:px-12 py-20 border-t border-[#262626]">
        <div className="max-w-2xl mx-auto text-center">
          <h2 className="text-3xl lg:text-4xl font-extrabold text-white mb-5">
            Ready to take control?
          </h2>
          <p className="text-text-secondary mb-8">
            Join thousands of users who track their finances with PennyWise. Free forever.
          </p>
          <Link to="/register">
            <Button variant="gradient" size="lg">
              Start Tracking for Free
            </Button>
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="px-6 lg:px-12 py-8 border-t border-[#262626]">
        <div className="flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2.5">
            <div className="w-7 h-7 rounded-lg bg-[#BFFF00] flex items-center justify-center">
              <span className="text-[#0A0A0A] font-bold text-xs">P</span>
            </div>
            <span className="text-sm text-text-secondary">PennyWise</span>
          </div>
          <p className="text-xs text-text-tertiary">
            &copy; {new Date().getFullYear()} PennyWise. Built with care for your financial wellbeing.
          </p>
        </div>
      </footer>
    </div>
  )
}
